services:

  postgres:
    image: postgres:17
    container_name: facilityquote-postgres
    environment:
      POSTGRES_DB: facilityquote
      POSTGRES_USER: facilityquote
      POSTGRES_PASSWORD: facilityquote
    ports:
      - "5432:5432"
    volumes:
      - facilityquote-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U facilityquote -d facilityquote"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  keycloak-db:
    image: postgres:17
    container_name: facilityquote-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - facilityquote

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    container_name: facilityquote-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    depends_on:
      - keycloak-db

    networks:
      - facilityquote

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: facilityquote-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@facilityquote.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - facilityquote-pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  facilityquote-postgres-data:
  facilityquote-pgadmin-data:
  keycloak-db-data:

networks:
  facilityquote: